# This is a basic workflow to help you get started with Actions

name: Make Thunderstore Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Upload pack to thunderstore
        run: |
          echo "# PACK CODE: $(curl 'https://thunderstore.io/api/experimental/legacyprofile/create/' \
            -s \
            -H 'authority: thunderstore.io' \
            -H 'accept: application/json, text/plain, */*' \
            -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) r2modman/3.1.34 Chrome/87.0.4280.141 Electron/11.5.0 Safari/537.36' \
            -H 'content-type: application/octet-stream' \
            -H 'sec-fetch-site: cross-site' \
            -H 'sec-fetch-mode: cors' \
            -H 'sec-fetch-dest: empty' \
            -H 'accept-language: en-US' \
            --data-binary $'#r2modman\n${zip -r modpack.zip && base64 modpack.zip}' \
            --compressed | sed -E 's/(\{"key":")(.*)("\})/\2/g')" >> "$GITHUB_STEP_SUMMARY"

