name: make-pr

on:
  workflow_dispatch:
    inputs:
      profile-code:
        type: string
        description: profile code exported from r2modman
        required: true
      commit-message:
        type: string
        description: description of your change
        required: true

env:
  zip_file: riceofrain.r2z

jobs:
  make-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt-get install unzip p7zip-full

      - name: download .r2z
        run: |
          response=$(curl -L https://gcdn.thunderstore.io/live/modpacks/legacyprofile/${{ github.event.inputs.profile-code }}/)
          prefix=#r2modman
          rm -rf pack/*
          echo "${response#$prefix}" | base64 --decode > $zip_file
          7z rn $zip_file $(7z l $zip_file | grep '\\' | awk '{ print $6, gensub(/\\/, "/", "g", $6); }' | paste -s)
          unzip $zip_file -d pack

      - name: upload .r2z as github artifact
        uses: actions/upload-artifact@v2
        with:
            name: build
            path: ${{ env.zip_file }}
        env:
            CI: true

      - name: setup git
        run: git config --global core.autocrlf input

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ github.event.inputs.commit-message }}
          title: ${{ github.event.inputs.commit-message }}
          body: "automated PR.\n\n**pack code:** `${{ github.event.inputs.profile-code }}`"
          add-paths: pack/**
          branch-suffix: short-commit-hash
          delete-branch: true
