name: make-pr

on:
  workflow_dispatch:
    inputs:
      profile-code:
        type: string
        description: profile code exported from r2modman
        required: true
      commit-message:
        type: string
        description: description of your change
        required: true

env:
  zip_file: riceofrain.r2z

jobs:
  make-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt-get install unzip

      - name: download .r2z
        run: |
          response=$(curl https://thunderstore.io/api/experimental/legacyprofile/get/${{ github.event.inputs.profile-code }}/)
          prefix=#r2modman
          rm -rf *
          echo "${response#$prefix}" | base64 --decode > $zip_file
          unzip $zip_file -d .

      - name: upload .r2z as github artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.zip_file }}
        env:
          CI: true

      - run: rm $zip_file

      - name: commit & push branch
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git checkout -b ${{ github.event.inputs.profile-code }}
          git commit -am ${{ github.event.inputs.commit-message }}
          git push --set-upstream origin ${{ github.event.inputs.profile-code }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.inputs.profile-code }}
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
            
            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
